version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "123456"
    command: ["redis-server", "--requirepass", "123456"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
