version: '3.7'
services:
  drools-workbench:
    image: kiegroup/drools-workbench:7.59.0.Final
    ports:
      - "8080:8080"
    environment:
      - KIE_SERVER_HOST=kie-server
      - KIE_SERVER_PORT=8080
  drools-kie-server:
    image: kiegroup/drools-kie-server:7.59.0.Final
    ports:
      - "8180:8180"
    environment:
      - KIE_SERVER_HOST=kie-server
      - KIE_SERVER_PORT=8180